### ISSUE TITLE
Profile picture choose image

### ISSUE THREAD

**Issue by lilylilylily123** [jarredthejellyfish/l-coin#3]
![image](https://user-images.githubusercontent.com/102743831/161220165-2ef97c6e-203f-4961-9e5a-6e2d57ed2499.png)
It says that I don't have a image uploaded, but I do have a custom pfp.

**Comment by jaredthejellyfish** [comment]
The `choose file` box does not have anything actively selected from your files for you to upload so it says that you have chosen no files.
